#!/bin/sh

out=$(whence zbrewfuncs >/dev/null)
if [ $? -eq 0 ]; then
	. zbrewfuncs
else
	echo "zbrew tools need to be in your PATH"
	exit 4
fi

#
# msf - for now - make this ZBREW_TGT_HLQ equal to ZBREW_SRC_HLQ
# and fix this when 'dzip' is added
#
export ZBREW_TGT_HLQ=${ZBREW_SRC_HLQ}
runivp() {
#set -x
	tempprefix="${ZBREW_TGT_HLQ}IGY630T"
	tempds=`mvstmp ${tempprefix}`
	dtouch -tseq $tempds

	jobcard="//IGYWIVP1   JOB ${ZBREW_JOBOPTS},${ZBREW_JOBPARMS}"
	decho "$jobcard" ${tempds}
	decho -a "//*
//PROCLIB JCLLIB ORDER=${ZBREW_TGT_HLQ}IGY630.SIGYPROC
//RUNIVP EXEC IGYWCLG,REGION=0M,
//  LNGPRFX=${ZBREW_TGT_HLQ}IGY630,
//  LIBPRFX=${ZBREW_CEEHLQ},
//  PARM.LKED='LIST,XREF,LET,MAP',
//  PARM.COBOL='RENT',
//  PARM.GO=''
//COBOL.SYSIN DD DISP=SHR,
//  DSN=${ZBREW_TGT_HLQ}IGY630.SIGYSAMP(IGYIVP)
//GO.SYSOUT DD SYSOUT=*
" ${tempds}

	job=`jsub $tempds`
	while true ; do
		output=`jls ${job}`
		if [ $? -eq 0 ]; then
			if [ "${output}" != '' ]; then 
				status=`echo ${output} | awk '{ print $4; }'`
				if [ "${status}" != 'AC' ]; then
					break
				fi
			fi
		fi
		sleep 1
	done
	rc=`echo ${output} | awk '{ print $5; }'`
	if [ "${rc}" != '0000' ]; then
		echo "IVP failed with RC:${rc}. Temporary JCL is in ${tempds}. Job output is in ${job}"
		exit 16
	fi

	drm $tempds
	exit 0
}

mydir=$(callerdir ${0})
props="${mydir}/../../zbrew/zbrewglobalprops.json"
zbrewpropse zbrew config "${props}"

out=`runivp`
rc=$?
if [ $rc -gt 0 ]; then
	echo "IVP failed. Installation aborted"
	echo "$out"
	exit $rc
fi

