#!/bin/sh
#set -x

out=$(whence zbrewfuncs >/dev/null)
if [ $? -eq 0 ]; then
	. zbrewfuncs
else
	echo "zbrew tools need to be in your PATH"
	exit 4
fi

crtds() {
	list=$1
	echo "$1" | awk '{ ds=$1; $1=""; attrs=$0; if ($ds != "") { rc=system("dtouch " attrs " " ds); if (rc > 0) { exit(rc); } } }'
	exit $?
}

crtzfs() {
	root=$1 
	middle='/usr/lpp/IBM/cobol/igyv6r3/'
	mkdir -p -m 755 ${root}${middle}
	rc=$?
	if [ $rc -gt 0 ]; then
		exit $rc
	fi

	mvscmdauth --pgm=IDCAMS --sysprint='*' --sysin=stdin <<zzz
   DEFINE CLUSTER(NAME(${ZBREW_HLQ}IGY630.ZFS) -
   LINEAR CYLINDERS(2 1) SHAREOPTIONS(3)
zzz
	rc=$?
	if [ $rc -gt 0 ]; then
		exit $rc
	fi
	mvscmdauth --pgm=IOEAGFMT --args="-aggregate ${ZBREW_HLQ}IGY630.ZFS -compat" --sysprint='*'
	rc=$?
	if [ $rc -gt 0 ]; then
		exit $rc
	fi
	/usr/sbin/mount -t zfs -f ${ZBREW_HLQ}IGY630.ZFS ${root}${middle}
	rc=$?
	if [ $rc -gt 0 ]; then
		exit $rc
	fi

	leaves='bin/.orig bin/IBM lib/nls/msg/C lib/nls/msg/Ja_JP include demo/oosample'
	for l in $leaves; do
		mkdir -p -m 755 ${root}${middle}${l}
		rc=$?
		if [ $rc -gt 0 ]; then
			exit $rc
		fi
	done
	exit 0
}

crtddef() {
targetsmpcntl=\
" SET   BDY(${ZBREW_HLQ}IGY630T).
 UCLIN.
  ADD DDDEF(SIGYMAC)
      DA(${ZBREW_HLQ}IGY630.SIGYMAC)
      UNIT(SYSALLDA)
      WAITFORDSN
      SHR.
  ADD DDDEF(SIGYCOMP)
      DA(${ZBREW_HLQ}IGY630.SIGYCOMP)
      UNIT(SYSALLDA)
      WAITFORDSN
      SHR.
  ADD DDDEF(SIGYPROC)
      DA(${ZBREW_HLQ}IGY630.SIGYPROC)
      UNIT(SYSALLDA)
      WAITFORDSN
      SHR.
  ADD DDDEF(SIGYSAMP)
      DA(${ZBREW_HLQ}IGY630.SIGYSAMP)
      UNIT(SYSALLDA)
      WAITFORDSN
      SHR.
  ADD DDDEF(AIGYHFS)
      DA(${ZBREW_HLQ}IGY630.AIGYHFS)
      UNIT(SYSALLDA)
      WAITFORDSN
      SHR.
  ADD DDDEF(AIGYMOD1)
      DA(${ZBREW_HLQ}IGY630.AIGYMOD1)
      UNIT(SYSALLDA)
      WAITFORDSN
      SHR.
  ADD DDDEF(AIGYSRC1)
      DA(${ZBREW_HLQ}IGY630.AIGYSRC1)
      UNIT(SYSALLDA)
      WAITFORDSN
      SHR.
  ADD DDDEF(SIGYHFS)
      PATH('${IGYROOT}/usr/lpp/IBM/cobol/igyv6r3/bin/IBM/').
 ENDUCL."

distsmpcntl=\
" SET   BDY(${ZBREW_HLQ}IGY630D).
 UCLIN.
  ADD DDDEF(AIGYHFS)
      DA(${ZBREW_HLQ}IGY630.AIGYHFS)
      UNIT(SYSALLDA)
      WAITFORDSN
      SHR.
  ADD DDDEF(AIGYMOD1)
      DA(${ZBREW_HLQ}IGY630.AIGYMOD1)
      UNIT(SYSALLDA)
      WAITFORDSN
      SHR.
  ADD DDDEF(AIGYSRC1)
      DA(${ZBREW_HLQ}IGY630.AIGYSRC1)
      UNIT(SYSALLDA)
      WAITFORDSN
      SHR.
 ENDUCL."

	mvscmdauth --pgm=GIMSMP --smpcsi=${ZBREW_HLQ}IGY630G.GLOBAL.CSI --smppts=${ZBREW_HLQ}IGY630G.SMPPTS --smplog='*' --smpout='*' --smprpt='*' --smplist='*' --sysprint='*'  --smpcntl=stdin <<zzz
${targetsmpcntl}
zzz
	rc=$?
	if [ $rc -gt 0 ]; then
		exit $rc
	fi

	mvscmdauth --pgm=GIMSMP --smpcsi=${ZBREW_HLQ}IGY630G.GLOBAL.CSI --smplog='*' --smpout='*' --smprpt='*' --smplist='*' --sysprint='*' --smpcntl=stdin <<zzz
${distsmpcntl}
zzz
	rc=$?
	exit $rc
}
mydir=$(callerdir ${0})
props="${mydir}/../../zbrew/properties/zbrew.properties"
. zbrewprops "${props}"
if [ $? -gt 0 ]; then
        echo "Internal Error. Unable to find ${props}" >&2
        exit 4
fi     
props="${mydir}/igy630install.properties"
. zbrewprops ${props}

ds="
    	${ZBREW_HLQ}IGY630.SIGYCOMP -s150M -ru
	${ZBREW_HLQ}IGY630.SIGYMAC -s1M
	${ZBREW_HLQ}IGY630.SIGYPROC -s1M
	${ZBREW_HLQ}IGY630.SIGYSAMP -s1M
"

out=`crtds "${ds}"`
rc=$?
if [ $rc -gt 0 ]; then
	echo "Dataset creation failed. Installation aborted"
	exit $rc
fi

out=`crtzfs "${IGYROOT}"`
rc=$?
if [ $rc -gt 0 ]; then
	echo "zFS File system creation failed. Installation aborted"
	exit $rc
fi

out=`crtddef`
rc=$?
if [ $rc -gt 0 ]; then
	echo "SMP Data Definition failed. Installation aborted"
	echo "$out"
	exit $rc
fi

exit 0

