#!/bin/sh
#set -x

out=$(whence zbrewfuncs >/dev/null)
if [ $? -eq 0 ]; then
	. zbrewfuncs
else
	echo "zbrew tools need to be in your PATH"
	exit 4
fi

props=$(callerdir "$0")"/../../zbrew/zbrewglobalprops.json"
zbrewpropse zbrew global ${props}

zosinfo=`uname -rsvI`
version=`echo ${zosinfo} | awk '{ print $3; }'`
if [ "${version}" != "02" ]; then
	echo "z/OS Version not supported. Must be 02"
	exit 16
fi
release=`echo ${zosinfo} | awk '{ print $2; }'`

case ${release} in
	'02.00' ) 
		ptfs='UI62788 UI62416 UI64723 UI62788'
		CHK_CSI=${CEE220_CSI}	
		;;
	'03.00' ) 
		ptfs='UI61308 UI61747 UI64724 UI65062'
		CHK_CSI=${CEE230_CSI}
		;;
	'04.00' ) 
		ptfs=''
		CHK_CSI=${CEE240_CSI}
		;;
	* ) echo "z/OS 2.${release} not supported for IGY630";;
esac

if [ "${ptfs}" = '' ]; then
	exit 0
fi

if [ "${CHK_CSI}" = "NONE" ]; then
	echo "No LE SMP/E CSI is available. Pre-requisites are assumed ok"
	exit 0
fi

out=`smpchkptf ${CHK_CSI} ${ptfs}`
rc=$?
if [ $rc -gt 0 ]; then
	echo ${out}
fi
exit $rc
